### PR TITLE
iot_button.c - fix data being overwritten.

### PR DESCRIPTION
**Pull request by DylanRobertBennett**
This change was copied from another users PR. https://github.com/espressif/esp-iot-solution/pull/202

### CODE REVIEW

**Comment by cmorganBE** [comment]
Lets wait until this PR lands into master imo.

**Comment by cmorganBE** [comment]
And you should review franz changes.

**Comment by franz-ms-muc** [comment]
why closed ?

**Comment by DylanRobertBennett** [comment]
@franz-ms-muc because these changes where merged to https://github.com/espressif/esp-iot-solution. So after the merge in espressif i pulled the latest from that repo and didn't need this branch any longer.

**Pull request closed without merging**
